/*
 * generated by Xtext 2.14.0
 */
package bz.erasmus.x400.xrpgle.xtext.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
class XRPGLEOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
