/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package bz.erasmus.x400.xrpgle.xtext.ide


/**
 * Use this class to register ide components.
 */
class XRPGLEIdeModule extends AbstractXRPGLEIdeModule {
}
