/*
 * generated by Xtext 2.14.0
 */
package bz.erasmus.x400.xrpgle.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XRPGLEStandaloneSetup extends XRPGLEStandaloneSetupGenerated {

	def static void doSetup() {
		new XRPGLEStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
