/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package bz.erasmus.x400.xrpgle.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class XRPGLERuntimeModule extends AbstractXRPGLERuntimeModule {
}
