/*
 * generated by Xtext 2.14.0
 */
package bz.erasmus.x400.xrpgle.xtext.ui.quickfix

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
class XRPGLEQuickfixProvider extends DefaultQuickfixProvider {

}
