/*
 * generated by Xtext 2.14.0
 */
package bz.erasmus.x400.xrpgle.xtext.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class XRPGLEValidator extends AbstractXRPGLEValidator {

}
